### ISSUE TITLE
lysp fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#922]
`brew install lysp` fails to build. See https://gist.github.com/rwhogg/e2bd5326effb21cdef2e

Message:
> /usr/bin/ld.bfd.real: /tmp/ccLlskkP.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:21: recipe for target 'gclysp' failed
make: *** [gclysp] Error 1

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

**Comment by sjackman** [comment]
Does `brew install gcc --with-glibc` work around this issue?

**Comment by sjackman** [comment]
I pushed faf5144 which *may* resolve this issue. Try it out.

**Comment by rwhogg** [comment]
> I pushed faf5144 which may resolve this issue. Try it out.
No luck, unfortunately. Same problem. That said, it did fix the failing libxmp test!

**Comment by rwhogg** [comment]
> brew install gcc --with-glibc && brew install lysp
No luck here either, but that's just because `glibc` fails to build (it says gcc-4.9 is not installed and the gcc I have is too old).

I was able to work around that with `brew install glibc --with-cc=gcc`, but that fails in the postinstall stage with "Inconsistency detected by ld.so: get-dynamic-info.h: 134: elf_get_dynamic_info: Assertion `info[15] == ((void *)0)' failed!"

I promptly removed `glibc` after seeing that, since I'm nervous about programs incorrectly linking to a broken libc. This issue is low priority, so no big deal.

**Comment by sjackman** [comment]
I've seen that error message before over here: https://github.com/Linuxbrew/linuxbrew/issues/126

GCC 4.8.4 is plenty new enough. It shouldn't complain about an old GCC. If you have been using this Linuxbrew installation for a while, and don't have `glibc` installed, I'd recommend starting over with a clean installation of Linuxbrew and start with `brew install gcc`, which will install `glibc` and `gcc`. Everything should be easier after that.

**Comment by sjackman** [comment]
Do you have `binutils` installed? If not, you can try `brew install binutils`.

**Comment by rwhogg** [comment]
`binutils` was installed as a dependency right before I started to build `glibc`.

The funny thing is, I've been using Homebrew's GCC 5.3 for a couple of months now, precisely because of that "your gcc is ancient" error message.

**Comment by sjackman** [comment]
> "your gcc is ancient" error message.

Does `glibc` give that error message? Can you quote it?

**Comment by rwhogg** [comment]
> Does `glibc` give that error message?
It originally came up a few months ago; I don't remember what formula was causing the problem. 

The exact text is "*** These critical programs are missing or too old: gcc". Which sounds to me like utter nonsense since the `gcc` in my PATH is Homebrew's 5.3 and the one in `/usr/bin` is 4.8.4.

I think you're right and I should probably reinstall from scratch. However, considering the massive number of packages I have installed at this point, I think I'm probably better off waiting until my next distro upgrade (I'm planning one in May).

Also, question: I need to keep track of which formulae fail for me, so I can eventually fix them. For a while, I had settled on only filing issues which I had effectively given up on and just tracking the rest on a [wiki page](https://github.com/rwhogg/linuxbrew/wiki/List-of-formulae-that-don't-build), but then decided I shouldn't hide the issues from you. For issues which don't have an immediate, obvious fix (for which I obviously just provide the PR straight away, per your earlier advice), what would you rather I do?

**Comment by sjackman** [comment]
> The exact text is "*** These critical programs are missing or too old: gcc". Which sounds to me like utter nonsense since the gcc in my PATH is Homebrew's 5.3 and the one in /usr/bin is 4.8.4.

That is nonsense. I think the `glibc` compiler check is failing somehow.

I changed the default behaviour of bottles today to install both `glibc` and `gcc` when the system's `glibc` is too old. Installing `glibc` without installing `gcc` was fraught with peril. `gcc` is often necessary since it provides the shared libraries `libgcc_s.so` and `libstdc++.so.6`.

Please do open an issue with a gist whenever you encounter a failed build. If someone else encounters that failed build as well, it's nice to have a history of the build failure corroborated by someone else.

**Comment by sjackman** [comment]
I want to add a `fails_with_os :linux, "GitHub issue number"` to mark formula that are known to fail.

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#147
