### ISSUE TITLE
voltdb fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#926]
`voltdb` fails to build on Ubuntu 14.04. See https://gist.github.com/rwhogg/e8915cf3c2c4880750a8

Message: `/home/bob/.linuxbrew/include/jni.h:45:20: fatal error: jni_md.h: No such file or directory`

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

**Comment by sjackman** [comment]
Does `brew install jdk voltdb` resolve this issue?

**Comment by rwhogg** [comment]
No, it doesn't. `jdk` was already installed at the time.

Looking in `~/.linuxbrew/include`, I see `jni.h` but no `jni_md.h`. There's one in `~/.linuxbrew/include/linux`, which follows what Ubuntu's OpenJDK7 package does. However, OpenJDK also includes a symlink to `jni_md.h` in its toplevel include folder, which Linuxbrew currently does not.

**Comment by sjackman** [comment]
Does adding the top-level symlink resolve it? If so, I'd suggest adding the symlink to `jdk`.

**Comment by rwhogg** [comment]
Yes, it does. `jdk7` could probably use it too.

**Comment by sjackman** [comment]
Great. If send a pull request, I'll merge it.

**Comment by rwhogg** [comment]
I think I've found the underlying problem. On Mac, [`java_requirement.rb](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/requirements/java_requirement.rb#L21) has the following:

```ruby
if (java_home/"include").exist? # Oracle JVM
      ENV.append_to_cflags "-I#{java_home}/include"
      ENV.append_to_cflags "-I#{java_home}/include/darwin"
    else # Apple JVM
      ENV.append_to_cflags "-I/System/Library/Frameworks/JavaVM.framework/Versions/Current/Headers/"
    end
```

On Linux, it's conditioned out with an `if OS.mac?`

I suspect (not tested yet) that if we switch `darwin` with `#{OS::NAME}` it will fix this build.

**Comment by rwhogg** [comment]
> I suspect (not tested yet) that if we switch darwin with #{OS::NAME} it will fix this build.

Not quite... there's a bit more to it than that. Nevertheless, I think this approach is going somewhere.

**Comment by sjackman** [comment]
Thanks for the sleuthing work, Bob.

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#143
