### ISSUE TITLE
x264 failed to build on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by retokromer** [Linuxbrew/linuxbrew#791]
The `brew gist-logs x264` output is:
https://gist.github.com/f5ad750d02af5cd278ab
(Sorry, I don't have the time to delve deeper into this now.)

**Comment by sjackman** [comment]
Thanks for the bug report, Reto. I don't have time either right now. Sorry. The relevant error is…
https://gist.github.com/anonymous/f5ad750d02af5cd278ab#file-02-make-L92
```
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_subpacket':
/home/why/ffmpeg-2.8.5/libavcodec/opusdec.c:379: undefined reference to `swr_is_initialized'
```

**Comment by retokromer** [comment]
Thank you, Shaun, for the hint!

**Comment by retokromer** [comment]
@sjackman: I saw you merged Homebrew into Linuxbrew. Now the installation works fine on my side. Therefore I guess this issue can be closed.

**Comment by sjackman** [comment]
Great. Glad to hear it.
