### ISSUE TITLE
txr fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#948]
`txr` fails to build on Ubuntu 14.04. See https://gist.github.com/rwhogg/87a85424efca56c55efd#file-01-configure-L27

```
Checking what C type we have for integers wider than "long long" ... ./configure: line 1017: [: gcc: integer expression expected
./configure: line 1017: $2: unbound variable
```

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

**Comment by rwhogg** [comment]
This seems to work if you set `--ccname=clang`, but since `llvm` is currently keg-only, I don't think that's an option just yet.

**Comment by rwhogg** [comment]
A few different results for comparison:

# --ccname=gcc-4.8
```
Last 15 lines from /home/bob/.cache/Homebrew/Logs/txr/02.make:
CC glob.c -> opt/glob.o
CC signal.c -> opt/signal.o
CC linenoise/linenoise.c -> opt/linenoise/linenoise.o
CC y.tab.c -> opt/y.tab.o
CC match.c -> opt/match.o
CC parser.c -> opt/parser.o
CC txr.c -> opt/txr.o
CC lex.yy.c -> opt/lex.yy.o
lex.yy.c: In function ‘yyensure_buffer_stack’:
lex.yy.c:3993:21: error: expected expression before ‘/’ token
   num_to_alloc = 1; // After all that talk, this was set to 1 anyways...
                     ^
Makefile:137: recipe for target 'opt/lex.yy.o' failed
make: *** [opt/lex.yy.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#148
